# global settings
title: "Portfolio - Patrícia Tozi"

# build settings
markdown: kramdown
plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-octicons

domain: patriciatozi.github.io       
url: https://patriciatozi.github.io  

sass:
  style: compressed
  # Where you keep your scss files
  sass_dir: docs/static/css/
  # Where sass should look for other scss